on:
  push:
    tags: 'v*'

name: 'bump-hombrew'

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1
        if: "!contains(github.ref, '-')" # skip prereleases
        with:
          formula-name: 'cleanup-heroku'
          homebrew-tap: 'kljensen/homebrew-tap'
          base-branch: 'main'
          commit-message: '{{formulaName}} {{version}}'
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
